language: python
python:
  - "3.7"

env:
  global:
    - PYTHONPATH=.

install:
  - pip install .
  - pip install coverage
  - pip install coveralls
  - pip install -r tests/requirements.txt

script:
  - coverage --omit="tests,examples"   run -m unittest discover tests

after_success:
  - coveralls
